---
label: default
hide_body: false
is_partial: false
fields:
- name: layout
  label: Layout
  type: text
  hidden: false
  default: default
- type: textarea
  name: text
  label: text
pages:
- _posts/2019-01-07-demo-post.md
