---
label: default
hide_body: false
is_partial: false
fields:
- type: textarea
  name: text
  label: text
  default: ''
- type: textarea
  name: post
  label: post
- type: blocks
pages:
- _posts/2019-01-07-demo-post.md
